services:
  postgres:
    image: postgres:15
    container_name: geenius-postgres
    environment:
      POSTGRES_USER: geenius_user
      POSTGRES_PASSWORD: geenius_password
      POSTGRES_DB: geenius_auth
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: